<?php

define('LANGUAGE_NEGOTIATION_SELECTION_PAGE', 'language-selection-page');

/**
 * Implements hook_menu().
 */
function i18n_selection_page_menu() {
  $items = array();

  $items['admin/config/regional/language/configure/selection_page'] = array(
    'title' => 'Language selection page',
    'description' => 'Configure the language selection page behavior',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('i18n_selection_page_admin'),
    'access arguments' => array('administer languages'),
    'file' => 'i18n_selection_page.admin.inc',
    'type' => MENU_VISIBLE_IN_BREADCRUMB
  );

  $items['language_selection'] = array(
    'description' => 'Language selection page',
    'page callback' => 'i18n_selection_page_selection_page',
    'access arguments' => array('access content'),
    'file' => 'i18n_selection_page.pages.inc',
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implementation of hook_language_negotiation_info().
 *
 * @return void
 */
function i18n_selection_page_language_negotiation_info() {
  $language_providers[LANGUAGE_NEGOTIATION_SELECTION_PAGE] = array(
    'types' => array(LANGUAGE_TYPE_CONTENT, LANGUAGE_TYPE_INTERFACE, LANGUAGE_TYPE_URL),
    'callbacks' => array(
      'language' => 'locale_language_from_url',
      'switcher' => 'locale_language_switcher_url',
      'url_rewrite' => 'locale_language_url_rewrite_url'
    ),
    'file' => drupal_get_path('module', 'i18n_selection_page') . '/i18n_selection_page.module',
    'weight' => 50,
    'name' => t('Selection Page'),
    'description' => t('Use a Selection Page to the visitor to choose it\'s language.'),
    'config' => 'admin/config/regional/language/configure/selection_page'
  );
  return $language_providers;
}

/**
 * Implements hook_init().
 */
function i18n_selection_page_init() {

  if (!language_negotiation_get_any(LANGUAGE_NEGOTIATION_SELECTION_PAGE)) {
    drupal_set_message("i18n selection page disabled.");
    return TRUE;
  }

  $language = $GLOBALS['language'];
  $error = FALSE;

  // Some checks
  if ($_GET['q'] == 'language_selection') $error = TRUE;
  if (!isset($_SERVER['SERVER_ADDR'])) $error = TRUE;

  if (!isset($language->provider) || $language->provider != LOCALE_LANGUAGE_NEGOTIATION_URL_FALLBACK) return;

  // Work on query
  $query = drupal_get_query_parameters();
  $query['destination'] = $_GET['q'];


  if (!$error) {
    //$url = url('language_selection', array('query' => $query, 'absolute' => FALSE, 'language' => LANGUAGE_NONE));
    //drupal_set_message("Redirect to $url",'warning');
    drupal_goto('language_selection', array('query' => $query, 'absolute' => FALSE, 'language' => LANGUAGE_NONE));
    //header("Location: $url");
    //exit;
  }
}

/**
* Implements hook_theme().
*/

function i18n_selection_page_theme() {
  return array(
    'i18n_selection_page' => array(
      'arguments' => array('data' => array()),
      'path' => drupal_get_path('module', 'i18n_selection_page') . '/themes',
      //'file' => '/i18n_selection_page.pages.inc',
      'template' => 'i18n_selection_page'
    ),
    'i18n_selection_page_body' => array(
      'arguments' => array('data' => array()),
      'path' => drupal_get_path('module', 'i18n_selection_page') . '/themes',
      //'file' => 'i18n_selection_page.pages.inc',
      'template' => 'i18n_selection_page_body'
    )
  );
}

/**
 * Implementation of hook_requirements().
 */
/*
function i18n_selection_page_requirements($phase) {
  module_load_include('inc', 'i18n_selection_page', 'includes/i18n_selection_page.helpers');

  $requirements = array();
  $t = get_t();
  $lang_list = language_list('enabled');
  $messages = _i18n_selection_page_error_messages();
  $language_count = _i18n_selection_page_check_language_count();

  if (variable_get('language_negotiation', LANGUAGE_NEGOTIATION_NONE) != 2) {
    $requirements['i18n_selection_page'] = array(
      'title' => 'I18N Selection Page',
      'value' => $t($messages['language_negotiation'], array(
                                                            '%setting_name' => t('Language negotiation'),
                                                            '%setting_value' => t('Path prefix with language fallback.'),
                                                            '@setting_url' => url('admin/settings/language/configure'),
                                                       )),
      'severity' => REQUIREMENT_ERROR
    );
    return $requirements;
  }

  if ($language_count['db'] != $language_count['vars']) {
    $requirements['i18n_selection_page'] = array(
      'title' => 'I18N Selection Page',
      'value' => $t($messages['language_count'], array('@language_count_db' => $language_count['db'], '@language_count_vars' => $language_count['vars'])),
      'severity' => REQUIREMENT_ERROR
    );
    return $requirements;
  }

  if ($language_count['db'] > 1) {
    $lang_list_without_prefix = array();
    foreach ($lang_list[1] as $lang) {
      if (empty($lang->prefix)) {
        $lang_list_without_prefix[$lang->language] = $t($messages['language_prefix'], array('@language_url' => url('admin/settings/language/edit/' . $lang->language), '@language_name' => $lang->name));
      }
    }
    if (count($lang_list_without_prefix) >= 1) {
      $requirements['i18n_selection_page'] = array(
        'title' => 'I18N Selection Page',
        'value' => implode('<br/>', $lang_list_without_prefix),
        'severity' => REQUIREMENT_WARNING
      );
    }
    else {
      $requirements['i18n_selection_page'] = array(
        'title' => 'I18N Selection Page',
        'value' => t($messages['language_all_good']),
        'severity' => REQUIREMENT_OK
      );
    }
  } else {
    $link = url('admin/settings/language');
    $requirements['i18n_selection_page'] = array(
      'title' => 'I18N Selection Page',
      'value' => $t($messages['language_only_one'], array('@link' => $link)),
      'severity' => REQUIREMENT_WARNING
    );
  }

  return $requirements;
}
*/